Repository caicloud/clientset, pull requests merged in 2018-04, with the labels that each got.

#51 chore(util): use api apps v1beta2 instead of extentions v1beta1
  util/controller/controller_ref_manager.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#52 feat(lb): add phase to PodStatus
  pkg/apis/loadbalance/v1alpha2/types.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XS

#47 feat(resource): add os details in machine env
  pkg/apis/resource/v1beta1/cluster.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, release-note-none, size/S

#53 feat(resource): add gpu info in machine env
  pkg/apis/resource/v1beta1/cluster.go
  pkg/apis/resource/v1beta1/zz_generated.deepcopy.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#57 fix(cmd): delete repeated slashes in OSX
  cmd/autogenerate.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#58 fix(resource): fix back storage type parameters
  pkg/apis/resource/v1beta1/storage.go
  pkg/apis/resource/v1beta1/zz_generated.deepcopy.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#62 feat(tenant): add gpu resource name
  pkg/apis/tenant/v1alpha1/type.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
